name: generate-difference

on: 
  - push
    
jobs:
  my_push:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run install
      run: |
        make install
    - name: Run linter
      run: |
        make lint
    - name: Test
      run: |
        make test
    - name: Test covarage
      uses: paambaati/codeclimate-action@v2.4.0
      with:
        coverageCommand: make test-coverage
        debug: true
