name: generate-difference

on: 
  - push
    
jobs:
  my_push:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run install
      run: |
        make install
    - name: Run linter
      run: |
        make lint
    - name: Test & code coverage
      uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: 599e0410625b6cf15ba6ebd453bb540ca3402be6e35ce81bd6d9e6f4fbca0c34
      with:
        coverageCommand: npm test-coverage
        debug: true
